-- Ensure the genres table is populated with the top genres from the Music API.
INSERT OR IGNORE INTO genres (name)
VALUES 
('rock'),
('electronic'),
('seen live'),
('alternative'),
('pop'),
('indie'),
('female vocalists'),
('metal'),
('alternative rock'),
('jazz'),
('classic rock'),
('ambient'),
('experimental'),
('folk'),
('indie rock'),
('punk'),
('Hip-Hop'),
('hard rock'),
('black metal'),
('instrumental'),
('singer-songwriter'),
('dance'),
('80s'),
('death metal'),
('Progressive rock'),
('heavy metal'),
('hardcore'),
('british'),
('soul'),
('chillout'),
('electronica'),
('rap'),
('industrial'),
('punk rock'),
('Classical'),
('Soundtrack'),
('blues'),
('thrash metal'),
('90s'),
('metalcore'),
('psychedelic'),
('acoustic'),
('japanese'),
('hip hop'),
('post-rock'),
('Progressive metal'),
('House'),
('german'),
('techno'),
('new wave');